// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package profile

import (
	"context"
	"time"
	"uuid"

	"github.com/rank1zen/kevin/internal/riot"
	"github.com/rank1zen/kevin/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRiotClient creates a new instance of MockRiotClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRiotClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRiotClient {
	mock := &MockRiotClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRiotClient is an autogenerated mock type for the RiotClient type
type MockRiotClient struct {
	mock.Mock
}

type MockRiotClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRiotClient) EXPECT() *MockRiotClient_Expecter {
	return &MockRiotClient_Expecter{mock: &_m.Mock}
}

// GetAccountByRiotID provides a mock function for the type MockRiotClient
func (_mock *MockRiotClient) GetAccountByRiotID(ctx context.Context, region string, name string, tag string) (*riot.Account, error) {
	ret := _mock.Called(ctx, region, name, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByRiotID")
	}

	var r0 *riot.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*riot.Account, error)); ok {
		return returnFunc(ctx, region, name, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *riot.Account); ok {
		r0 = returnFunc(ctx, region, name, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*riot.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, region, name, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRiotClient_GetAccountByRiotID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByRiotID'
type MockRiotClient_GetAccountByRiotID_Call struct {
	*mock.Call
}

// GetAccountByRiotID is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - name string
//   - tag string
func (_e *MockRiotClient_Expecter) GetAccountByRiotID(ctx any, region any, name any, tag any) *MockRiotClient_GetAccountByRiotID_Call {
	return &MockRiotClient_GetAccountByRiotID_Call{Call: _e.mock.On("GetAccountByRiotID", ctx, region, name, tag)}
}

func (_c *MockRiotClient_GetAccountByRiotID_Call) Run(run func(ctx context.Context, region string, name string, tag string)) *MockRiotClient_GetAccountByRiotID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRiotClient_GetAccountByRiotID_Call) Return(account *riot.Account, err error) *MockRiotClient_GetAccountByRiotID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockRiotClient_GetAccountByRiotID_Call) RunAndReturn(run func(ctx context.Context, region string, name string, tag string) (*riot.Account, error)) *MockRiotClient_GetAccountByRiotID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByPUUID provides a mock function for the type MockRiotClient
func (_mock *MockRiotClient) GetAccountByPUUID(ctx context.Context, region string, puuid string) (*riot.Account, error) {
	ret := _mock.Called(ctx, region, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByPUUID")
	}

	var r0 *riot.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*riot.Account, error)); ok {
		return returnFunc(ctx, region, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *riot.Account); ok {
		r0 = returnFunc(ctx, region, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*riot.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, region, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRiotClient_GetAccountByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByPUUID'
type MockRiotClient_GetAccountByPUUID_Call struct {
	*mock.Call
}

// GetAccountByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - puuid string
func (_e *MockRiotClient_Expecter) GetAccountByPUUID(ctx any, region any, puuid any) *MockRiotClient_GetAccountByPUUID_Call {
	return &MockRiotClient_GetAccountByPUUID_Call{Call: _e.mock.On("GetAccountByPUUID", ctx, region, puuid)}
}

func (_c *MockRiotClient_GetAccountByPUUID_Call) Run(run func(ctx context.Context, region string, puuid string)) *MockRiotClient_GetAccountByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockRiotClient_GetAccountByPUUID_Call) Return(account *riot.Account, err error) *MockRiotClient_GetAccountByPUUID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockRiotClient_GetAccountByPUUID_Call) RunAndReturn(run func(ctx context.Context, region string, puuid string) (*riot.Account, error)) *MockRiotClient_GetAccountByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeagueEntriesByPUUID provides a mock function for the type MockRiotClient
func (_mock *MockRiotClient) GetLeagueEntriesByPUUID(ctx context.Context, region string, puuid string) (riot.LeagueList, error) {
	ret := _mock.Called(ctx, region, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetLeagueEntriesByPUUID")
	}

	var r0 riot.LeagueList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (riot.LeagueList, error)); ok {
		return returnFunc(ctx, region, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) riot.LeagueList); ok {
		r0 = returnFunc(ctx, region, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(riot.LeagueList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, region, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRiotClient_GetLeagueEntriesByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeagueEntriesByPUUID'
type MockRiotClient_GetLeagueEntriesByPUUID_Call struct {
	*mock.Call
}

// GetLeagueEntriesByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - puuid string
func (_e *MockRiotClient_Expecter) GetLeagueEntriesByPUUID(ctx any, region any, puuid any) *MockRiotClient_GetLeagueEntriesByPUUID_Call {
	return &MockRiotClient_GetLeagueEntriesByPUUID_Call{Call: _e.mock.On("GetLeagueEntriesByPUUID", ctx, region, puuid)}
}

func (_c *MockRiotClient_GetLeagueEntriesByPUUID_Call) Run(run func(ctx context.Context, region string, puuid string)) *MockRiotClient_GetLeagueEntriesByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRiotClient_GetLeagueEntriesByPUUID_Call) Return(leagueList riot.LeagueList, err error) *MockRiotClient_GetLeagueEntriesByPUUID_Call {
	_c.Call.Return(leagueList, err)
	return _c
}

func (_c *MockRiotClient_GetLeagueEntriesByPUUID_Call) RunAndReturn(run func(ctx context.Context, region string, puuid string) (riot.LeagueList, error)) *MockRiotClient_GetLeagueEntriesByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummoner provides a mock function for the type MockRiotClient
func (_mock *MockRiotClient) GetSummoner(ctx context.Context, region string, puuid string) (*riot.Summoner, error) {
	ret := _mock.Called(ctx, region, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetSummoner")
	}

	var r0 *riot.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*riot.Summoner, error)); ok {
		return returnFunc(ctx, region, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *riot.Summoner); ok {
		r0 = returnFunc(ctx, region, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*riot.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, region, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRiotClient_GetSummoner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummoner'
type MockRiotClient_GetSummoner_Call struct {
	*mock.Call
}

// GetSummoner is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - puuid string
func (_e *MockRiotClient_Expecter) GetSummoner(ctx any, region any, puuid any) *MockRiotClient_GetSummoner_Call {
	return &MockRiotClient_GetSummoner_Call{Call: _e.mock.On("GetSummoner", ctx, region, puuid)}
}

func (_c *MockRiotClient_GetSummoner_Call) Run(run func(ctx context.Context, region string, puuid string)) *MockRiotClient_GetSummoner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRiotClient_GetSummoner_Call) Return(summoner *riot.Summoner, err error) *MockRiotClient_GetSummoner_Call {
	_c.Call.Return(summoner, err)
	return _c
}

func (_c *MockRiotClient_GetSummoner_Call) RunAndReturn(run func(ctx context.Context, region string, puuid string) (*riot.Summoner, error)) *MockRiotClient_GetSummoner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AggregateAverageParticipantForChampionIDByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) AggregateAverageParticipantForChampionIDByPUUID(ctx context.Context, puuid string) ([]*store.AggregateAverageParticipantForChampionID, error) {
	ret := _mock.Called(ctx, puuid)

	if len(ret) == 0 {
		panic("no return value specified for AggregateAverageParticipantForChampionIDByPUUID")
	}

	var r0 []*store.AggregateAverageParticipantForChampionID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*store.AggregateAverageParticipantForChampionID, error)); ok {
		return returnFunc(ctx, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*store.AggregateAverageParticipantForChampionID); ok {
		r0 = returnFunc(ctx, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.AggregateAverageParticipantForChampionID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateAverageParticipantForChampionIDByPUUID'
type MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call struct {
	*mock.Call
}

// AggregateAverageParticipantForChampionIDByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
func (_e *MockStore_Expecter) AggregateAverageParticipantForChampionIDByPUUID(ctx any, puuid any) *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call {
	return &MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call{Call: _e.mock.On("AggregateAverageParticipantForChampionIDByPUUID", ctx, puuid)}
}

func (_c *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call) Run(run func(ctx context.Context, puuid string)) *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call) Return(aggregateAverageParticipantForChampionIDs []*store.AggregateAverageParticipantForChampionID, err error) *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call {
	_c.Call.Return(aggregateAverageParticipantForChampionIDs, err)
	return _c
}

func (_c *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string) ([]*store.AggregateAverageParticipantForChampionID, error)) *MockStore_AggregateAverageParticipantForChampionIDByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type MockStore
func (_mock *MockStore) Begin(ctx context.Context) (Store, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Store, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Store); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockStore_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Begin(ctx any) *MockStore_Begin_Call {
	return &MockStore_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockStore_Begin_Call) Run(run func(ctx context.Context)) *MockStore_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Begin_Call) Return(store1 Store, err error) *MockStore_Begin_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStore_Begin_Call) RunAndReturn(run func(ctx context.Context) (Store, error)) *MockStore_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockStore
func (_mock *MockStore) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockStore_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Commit(ctx any) *MockStore_Commit_Call {
	return &MockStore_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockStore_Commit_Call) Run(run func(ctx context.Context)) *MockStore_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Commit_Call) Return(err error) *MockStore_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockStore_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMatch provides a mock function for the type MockStore
func (_mock *MockStore) CreateMatch(ctx context.Context, req store.CreateMatch) (*store.Match, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatch")
	}

	var r0 *store.Match
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateMatch) (*store.Match, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateMatch) *store.Match); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Match)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateMatch) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatch'
type MockStore_CreateMatch_Call struct {
	*mock.Call
}

// CreateMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req store.CreateMatch
func (_e *MockStore_Expecter) CreateMatch(ctx any, req any) *MockStore_CreateMatch_Call {
	return &MockStore_CreateMatch_Call{Call: _e.mock.On("CreateMatch", ctx, req)}
}

func (_c *MockStore_CreateMatch_Call) Run(run func(ctx context.Context, req store.CreateMatch)) *MockStore_CreateMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateMatch
		if args[1] != nil {
			arg1 = args[1].(store.CreateMatch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateMatch_Call) Return(match *store.Match, err error) *MockStore_CreateMatch_Call {
	_c.Call.Return(match, err)
	return _c
}

func (_c *MockStore_CreateMatch_Call) RunAndReturn(run func(ctx context.Context, req store.CreateMatch) (*store.Match, error)) *MockStore_CreateMatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateParticipant provides a mock function for the type MockStore
func (_mock *MockStore) CreateParticipant(ctx context.Context, req store.CreateParticipant) (*store.Participant, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateParticipant")
	}

	var r0 *store.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateParticipant) (*store.Participant, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateParticipant) *store.Participant); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateParticipant) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateParticipant'
type MockStore_CreateParticipant_Call struct {
	*mock.Call
}

// CreateParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - req store.CreateParticipant
func (_e *MockStore_Expecter) CreateParticipant(ctx any, req any) *MockStore_CreateParticipant_Call {
	return &MockStore_CreateParticipant_Call{Call: _e.mock.On("CreateParticipant", ctx, req)}
}

func (_c *MockStore_CreateParticipant_Call) Run(run func(ctx context.Context, req store.CreateParticipant)) *MockStore_CreateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateParticipant
		if args[1] != nil {
			arg1 = args[1].(store.CreateParticipant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateParticipant_Call) Return(participant *store.Participant, err error) *MockStore_CreateParticipant_Call {
	_c.Call.Return(participant, err)
	return _c
}

func (_c *MockStore_CreateParticipant_Call) RunAndReturn(run func(ctx context.Context, req store.CreateParticipant) (*store.Participant, error)) *MockStore_CreateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRank provides a mock function for the type MockStore
func (_mock *MockStore) CreateRank(ctx context.Context, req store.CreateRank) (*store.Rank, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRank")
	}

	var r0 *store.Rank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateRank) (*store.Rank, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateRank) *store.Rank); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Rank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateRank) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRank'
type MockStore_CreateRank_Call struct {
	*mock.Call
}

// CreateRank is a helper method to define mock.On call
//   - ctx context.Context
//   - req store.CreateRank
func (_e *MockStore_Expecter) CreateRank(ctx any, req any) *MockStore_CreateRank_Call {
	return &MockStore_CreateRank_Call{Call: _e.mock.On("CreateRank", ctx, req)}
}

func (_c *MockStore_CreateRank_Call) Run(run func(ctx context.Context, req store.CreateRank)) *MockStore_CreateRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateRank
		if args[1] != nil {
			arg1 = args[1].(store.CreateRank)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateRank_Call) Return(rank *store.Rank, err error) *MockStore_CreateRank_Call {
	_c.Call.Return(rank, err)
	return _c
}

func (_c *MockStore_CreateRank_Call) RunAndReturn(run func(ctx context.Context, req store.CreateRank) (*store.Rank, error)) *MockStore_CreateRank_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRankHistory provides a mock function for the type MockStore
func (_mock *MockStore) CreateRankHistory(ctx context.Context, req store.CreateRankHistory) (*store.RankHistory, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRankHistory")
	}

	var r0 *store.RankHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateRankHistory) (*store.RankHistory, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateRankHistory) *store.RankHistory); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RankHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateRankHistory) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateRankHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRankHistory'
type MockStore_CreateRankHistory_Call struct {
	*mock.Call
}

// CreateRankHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req store.CreateRankHistory
func (_e *MockStore_Expecter) CreateRankHistory(ctx any, req any) *MockStore_CreateRankHistory_Call {
	return &MockStore_CreateRankHistory_Call{Call: _e.mock.On("CreateRankHistory", ctx, req)}
}

func (_c *MockStore_CreateRankHistory_Call) Run(run func(ctx context.Context, req store.CreateRankHistory)) *MockStore_CreateRankHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateRankHistory
		if args[1] != nil {
			arg1 = args[1].(store.CreateRankHistory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateRankHistory_Call) Return(rankHistory *store.RankHistory, err error) *MockStore_CreateRankHistory_Call {
	_c.Call.Return(rankHistory, err)
	return _c
}

func (_c *MockStore_CreateRankHistory_Call) RunAndReturn(run func(ctx context.Context, req store.CreateRankHistory) (*store.RankHistory, error)) *MockStore_CreateRankHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSummoner provides a mock function for the type MockStore
func (_mock *MockStore) CreateSummoner(ctx context.Context, req store.CreateSummoner) (*store.Summoner, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSummoner")
	}

	var r0 *store.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateSummoner) (*store.Summoner, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateSummoner) *store.Summoner); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateSummoner) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSummoner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSummoner'
type MockStore_CreateSummoner_Call struct {
	*mock.Call
}

// CreateSummoner is a helper method to define mock.On call
//   - ctx context.Context
//   - req store.CreateSummoner
func (_e *MockStore_Expecter) CreateSummoner(ctx any, req any) *MockStore_CreateSummoner_Call {
	return &MockStore_CreateSummoner_Call{Call: _e.mock.On("CreateSummoner", ctx, req)}
}

func (_c *MockStore_CreateSummoner_Call) Run(run func(ctx context.Context, req store.CreateSummoner)) *MockStore_CreateSummoner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateSummoner
		if args[1] != nil {
			arg1 = args[1].(store.CreateSummoner)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateSummoner_Call) Return(summoner *store.Summoner, err error) *MockStore_CreateSummoner_Call {
	_c.Call.Return(summoner, err)
	return _c
}

func (_c *MockStore_CreateSummoner_Call) RunAndReturn(run func(ctx context.Context, req store.CreateSummoner) (*store.Summoner, error)) *MockStore_CreateSummoner_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchByMatchID provides a mock function for the type MockStore
func (_mock *MockStore) GetMatchByMatchID(ctx context.Context, matchID string) (*store.Match, error) {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchByMatchID")
	}

	var r0 *store.Match
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.Match, error)); ok {
		return returnFunc(ctx, matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.Match); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Match)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetMatchByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchByMatchID'
type MockStore_GetMatchByMatchID_Call struct {
	*mock.Call
}

// GetMatchByMatchID is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
func (_e *MockStore_Expecter) GetMatchByMatchID(ctx any, matchID any) *MockStore_GetMatchByMatchID_Call {
	return &MockStore_GetMatchByMatchID_Call{Call: _e.mock.On("GetMatchByMatchID", ctx, matchID)}
}

func (_c *MockStore_GetMatchByMatchID_Call) Run(run func(ctx context.Context, matchID string)) *MockStore_GetMatchByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetMatchByMatchID_Call) Return(match *store.Match, err error) *MockStore_GetMatchByMatchID_Call {
	_c.Call.Return(match, err)
	return _c
}

func (_c *MockStore_GetMatchByMatchID_Call) RunAndReturn(run func(ctx context.Context, matchID string) (*store.Match, error)) *MockStore_GetMatchByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) GetMatchByPUUID(ctx context.Context, puuid string, req store.GetMatchByPUUIDPageParams) ([]*store.Match, store.GetMatchByPUUIDPageParams, error) {
	ret := _mock.Called(ctx, puuid, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchByPUUID")
	}

	var r0 []*store.Match
	var r1 store.GetMatchByPUUIDPageParams
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.GetMatchByPUUIDPageParams) ([]*store.Match, store.GetMatchByPUUIDPageParams, error)); ok {
		return returnFunc(ctx, puuid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.GetMatchByPUUIDPageParams) []*store.Match); ok {
		r0 = returnFunc(ctx, puuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Match)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, store.GetMatchByPUUIDPageParams) store.GetMatchByPUUIDPageParams); ok {
		r1 = returnFunc(ctx, puuid, req)
	} else {
		r1 = ret.Get(1).(store.GetMatchByPUUIDPageParams)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, store.GetMatchByPUUIDPageParams) error); ok {
		r2 = returnFunc(ctx, puuid, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_GetMatchByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchByPUUID'
type MockStore_GetMatchByPUUID_Call struct {
	*mock.Call
}

// GetMatchByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
//   - req store.GetMatchByPUUIDPageParams
func (_e *MockStore_Expecter) GetMatchByPUUID(ctx any, puuid any, req any) *MockStore_GetMatchByPUUID_Call {
	return &MockStore_GetMatchByPUUID_Call{Call: _e.mock.On("GetMatchByPUUID", ctx, puuid, req)}
}

func (_c *MockStore_GetMatchByPUUID_Call) Run(run func(ctx context.Context, puuid string, req store.GetMatchByPUUIDPageParams)) *MockStore_GetMatchByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 store.GetMatchByPUUIDPageParams
		if args[2] != nil {
			arg2 = args[2].(store.GetMatchByPUUIDPageParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetMatchByPUUID_Call) Return(matchs []*store.Match, getMatchByPUUIDPageParams store.GetMatchByPUUIDPageParams, err error) *MockStore_GetMatchByPUUID_Call {
	_c.Call.Return(matchs, getMatchByPUUIDPageParams, err)
	return _c
}

func (_c *MockStore_GetMatchByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string, req store.GetMatchByPUUIDPageParams) ([]*store.Match, store.GetMatchByPUUIDPageParams, error)) *MockStore_GetMatchByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByMatchID provides a mock function for the type MockStore
func (_mock *MockStore) GetParticipantByMatchID(ctx context.Context, matchID string) ([]*store.Participant, error) {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByMatchID")
	}

	var r0 []*store.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*store.Participant, error)); ok {
		return returnFunc(ctx, matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*store.Participant); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetParticipantByMatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByMatchID'
type MockStore_GetParticipantByMatchID_Call struct {
	*mock.Call
}

// GetParticipantByMatchID is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
func (_e *MockStore_Expecter) GetParticipantByMatchID(ctx any, matchID any) *MockStore_GetParticipantByMatchID_Call {
	return &MockStore_GetParticipantByMatchID_Call{Call: _e.mock.On("GetParticipantByMatchID", ctx, matchID)}
}

func (_c *MockStore_GetParticipantByMatchID_Call) Run(run func(ctx context.Context, matchID string)) *MockStore_GetParticipantByMatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetParticipantByMatchID_Call) Return(participants []*store.Participant, err error) *MockStore_GetParticipantByMatchID_Call {
	_c.Call.Return(participants, err)
	return _c
}

func (_c *MockStore_GetParticipantByMatchID_Call) RunAndReturn(run func(ctx context.Context, matchID string) ([]*store.Participant, error)) *MockStore_GetParticipantByMatchID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByMatchIDAndPUUID provides a mock function for the type MockStore
func (_mock *MockStore) GetParticipantByMatchIDAndPUUID(ctx context.Context, matchID string, puuid string) (*store.Participant, error) {
	ret := _mock.Called(ctx, matchID, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByMatchIDAndPUUID")
	}

	var r0 *store.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*store.Participant, error)); ok {
		return returnFunc(ctx, matchID, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *store.Participant); ok {
		r0 = returnFunc(ctx, matchID, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, matchID, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetParticipantByMatchIDAndPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByMatchIDAndPUUID'
type MockStore_GetParticipantByMatchIDAndPUUID_Call struct {
	*mock.Call
}

// GetParticipantByMatchIDAndPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - puuid string
func (_e *MockStore_Expecter) GetParticipantByMatchIDAndPUUID(ctx any, matchID any, puuid any) *MockStore_GetParticipantByMatchIDAndPUUID_Call {
	return &MockStore_GetParticipantByMatchIDAndPUUID_Call{Call: _e.mock.On("GetParticipantByMatchIDAndPUUID", ctx, matchID, puuid)}
}

func (_c *MockStore_GetParticipantByMatchIDAndPUUID_Call) Run(run func(ctx context.Context, matchID string, puuid string)) *MockStore_GetParticipantByMatchIDAndPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetParticipantByMatchIDAndPUUID_Call) Return(participant *store.Participant, err error) *MockStore_GetParticipantByMatchIDAndPUUID_Call {
	_c.Call.Return(participant, err)
	return _c
}

func (_c *MockStore_GetParticipantByMatchIDAndPUUID_Call) RunAndReturn(run func(ctx context.Context, matchID string, puuid string) (*store.Participant, error)) *MockStore_GetParticipantByMatchIDAndPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByPUUIDAndMatchIDs provides a mock function for the type MockStore
func (_mock *MockStore) GetParticipantByPUUIDAndMatchIDs(ctx context.Context, puuid string, matchIDs []string) ([]*store.Participant, error) {
	ret := _mock.Called(ctx, puuid, matchIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByPUUIDAndMatchIDs")
	}

	var r0 []*store.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]*store.Participant, error)); ok {
		return returnFunc(ctx, puuid, matchIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []*store.Participant); ok {
		r0 = returnFunc(ctx, puuid, matchIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, puuid, matchIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetParticipantByPUUIDAndMatchIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByPUUIDAndMatchIDs'
type MockStore_GetParticipantByPUUIDAndMatchIDs_Call struct {
	*mock.Call
}

// GetParticipantByPUUIDAndMatchIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
//   - matchIDs []string
func (_e *MockStore_Expecter) GetParticipantByPUUIDAndMatchIDs(ctx any, puuid any, matchIDs any) *MockStore_GetParticipantByPUUIDAndMatchIDs_Call {
	return &MockStore_GetParticipantByPUUIDAndMatchIDs_Call{Call: _e.mock.On("GetParticipantByPUUIDAndMatchIDs", ctx, puuid, matchIDs)}
}

func (_c *MockStore_GetParticipantByPUUIDAndMatchIDs_Call) Run(run func(ctx context.Context, puuid string, matchIDs []string)) *MockStore_GetParticipantByPUUIDAndMatchIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetParticipantByPUUIDAndMatchIDs_Call) Return(participants []*store.Participant, err error) *MockStore_GetParticipantByPUUIDAndMatchIDs_Call {
	_c.Call.Return(participants, err)
	return _c
}

func (_c *MockStore_GetParticipantByPUUIDAndMatchIDs_Call) RunAndReturn(run func(ctx context.Context, puuid string, matchIDs []string) ([]*store.Participant, error)) *MockStore_GetParticipantByPUUIDAndMatchIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRankByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) GetRankByPUUID(ctx context.Context, puuid string) (*store.Rank, error) {
	ret := _mock.Called(ctx, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetRankByPUUID")
	}

	var r0 *store.Rank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.Rank, error)); ok {
		return returnFunc(ctx, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.Rank); ok {
		r0 = returnFunc(ctx, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Rank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRankByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRankByPUUID'
type MockStore_GetRankByPUUID_Call struct {
	*mock.Call
}

// GetRankByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
func (_e *MockStore_Expecter) GetRankByPUUID(ctx any, puuid any) *MockStore_GetRankByPUUID_Call {
	return &MockStore_GetRankByPUUID_Call{Call: _e.mock.On("GetRankByPUUID", ctx, puuid)}
}

func (_c *MockStore_GetRankByPUUID_Call) Run(run func(ctx context.Context, puuid string)) *MockStore_GetRankByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetRankByPUUID_Call) Return(rank *store.Rank, err error) *MockStore_GetRankByPUUID_Call {
	_c.Call.Return(rank, err)
	return _c
}

func (_c *MockStore_GetRankByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string) (*store.Rank, error)) *MockStore_GetRankByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRankByPUUIDs provides a mock function for the type MockStore
func (_mock *MockStore) GetRankByPUUIDs(ctx context.Context, puuids []string) ([]*store.Rank, error) {
	ret := _mock.Called(ctx, puuids)

	if len(ret) == 0 {
		panic("no return value specified for GetRankByPUUIDs")
	}

	var r0 []*store.Rank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*store.Rank, error)); ok {
		return returnFunc(ctx, puuids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*store.Rank); ok {
		r0 = returnFunc(ctx, puuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Rank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, puuids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRankByPUUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRankByPUUIDs'
type MockStore_GetRankByPUUIDs_Call struct {
	*mock.Call
}

// GetRankByPUUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - puuids []string
func (_e *MockStore_Expecter) GetRankByPUUIDs(ctx any, puuids any) *MockStore_GetRankByPUUIDs_Call {
	return &MockStore_GetRankByPUUIDs_Call{Call: _e.mock.On("GetRankByPUUIDs", ctx, puuids)}
}

func (_c *MockStore_GetRankByPUUIDs_Call) Run(run func(ctx context.Context, puuids []string)) *MockStore_GetRankByPUUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetRankByPUUIDs_Call) Return(ranks []*store.Rank, err error) *MockStore_GetRankByPUUIDs_Call {
	_c.Call.Return(ranks, err)
	return _c
}

func (_c *MockStore_GetRankByPUUIDs_Call) RunAndReturn(run func(ctx context.Context, puuids []string) ([]*store.Rank, error)) *MockStore_GetRankByPUUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRankHistoryByID provides a mock function for the type MockStore
func (_mock *MockStore) GetRankHistoryByID(ctx context.Context, id uuid.UUID) (*store.RankHistory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRankHistoryByID")
	}

	var r0 *store.RankHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*store.RankHistory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *store.RankHistory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RankHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRankHistoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRankHistoryByID'
type MockStore_GetRankHistoryByID_Call struct {
	*mock.Call
}

// GetRankHistoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStore_Expecter) GetRankHistoryByID(ctx any, id any) *MockStore_GetRankHistoryByID_Call {
	return &MockStore_GetRankHistoryByID_Call{Call: _e.mock.On("GetRankHistoryByID", ctx, id)}
}

func (_c *MockStore_GetRankHistoryByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetRankHistoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetRankHistoryByID_Call) Return(rankHistory *store.RankHistory, err error) *MockStore_GetRankHistoryByID_Call {
	_c.Call.Return(rankHistory, err)
	return _c
}

func (_c *MockStore_GetRankHistoryByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*store.RankHistory, error)) *MockStore_GetRankHistoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRankHistoryByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) GetRankHistoryByPUUID(ctx context.Context, puuid string, start time.Time, end time.Time) ([]*store.RankHistory, error) {
	ret := _mock.Called(ctx, puuid, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetRankHistoryByPUUID")
	}

	var r0 []*store.RankHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*store.RankHistory, error)); ok {
		return returnFunc(ctx, puuid, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*store.RankHistory); ok {
		r0 = returnFunc(ctx, puuid, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.RankHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, puuid, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRankHistoryByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRankHistoryByPUUID'
type MockStore_GetRankHistoryByPUUID_Call struct {
	*mock.Call
}

// GetRankHistoryByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
//   - start time.Time
//   - end time.Time
func (_e *MockStore_Expecter) GetRankHistoryByPUUID(ctx any, puuid any, start any, end any) *MockStore_GetRankHistoryByPUUID_Call {
	return &MockStore_GetRankHistoryByPUUID_Call{Call: _e.mock.On("GetRankHistoryByPUUID", ctx, puuid, start, end)}
}

func (_c *MockStore_GetRankHistoryByPUUID_Call) Run(run func(ctx context.Context, puuid string, start time.Time, end time.Time)) *MockStore_GetRankHistoryByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_GetRankHistoryByPUUID_Call) Return(rankHistorys []*store.RankHistory, err error) *MockStore_GetRankHistoryByPUUID_Call {
	_c.Call.Return(rankHistorys, err)
	return _c
}

func (_c *MockStore_GetRankHistoryByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string, start time.Time, end time.Time) ([]*store.RankHistory, error)) *MockStore_GetRankHistoryByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummonerByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) GetSummonerByPUUID(ctx context.Context, puuid string) (*store.Summoner, error) {
	ret := _mock.Called(ctx, puuid)

	if len(ret) == 0 {
		panic("no return value specified for GetSummonerByPUUID")
	}

	var r0 *store.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.Summoner, error)); ok {
		return returnFunc(ctx, puuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.Summoner); ok {
		r0 = returnFunc(ctx, puuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, puuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSummonerByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummonerByPUUID'
type MockStore_GetSummonerByPUUID_Call struct {
	*mock.Call
}

// GetSummonerByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
func (_e *MockStore_Expecter) GetSummonerByPUUID(ctx any, puuid any) *MockStore_GetSummonerByPUUID_Call {
	return &MockStore_GetSummonerByPUUID_Call{Call: _e.mock.On("GetSummonerByPUUID", ctx, puuid)}
}

func (_c *MockStore_GetSummonerByPUUID_Call) Run(run func(ctx context.Context, puuid string)) *MockStore_GetSummonerByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetSummonerByPUUID_Call) Return(summoner *store.Summoner, err error) *MockStore_GetSummonerByPUUID_Call {
	_c.Call.Return(summoner, err)
	return _c
}

func (_c *MockStore_GetSummonerByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string) (*store.Summoner, error)) *MockStore_GetSummonerByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummonerByRegionNameTag provides a mock function for the type MockStore
func (_mock *MockStore) GetSummonerByRegionNameTag(ctx context.Context, region string, name string, tag string) (*store.Summoner, error) {
	ret := _mock.Called(ctx, region, name, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetSummonerByRegionNameTag")
	}

	var r0 *store.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*store.Summoner, error)); ok {
		return returnFunc(ctx, region, name, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *store.Summoner); ok {
		r0 = returnFunc(ctx, region, name, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, region, name, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSummonerByRegionNameTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummonerByRegionNameTag'
type MockStore_GetSummonerByRegionNameTag_Call struct {
	*mock.Call
}

// GetSummonerByRegionNameTag is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - name string
//   - tag string
func (_e *MockStore_Expecter) GetSummonerByRegionNameTag(ctx any, region any, name any, tag any) *MockStore_GetSummonerByRegionNameTag_Call {
	return &MockStore_GetSummonerByRegionNameTag_Call{Call: _e.mock.On("GetSummonerByRegionNameTag", ctx, region, name, tag)}
}

func (_c *MockStore_GetSummonerByRegionNameTag_Call) Run(run func(ctx context.Context, region string, name string, tag string)) *MockStore_GetSummonerByRegionNameTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_GetSummonerByRegionNameTag_Call) Return(summoner *store.Summoner, err error) *MockStore_GetSummonerByRegionNameTag_Call {
	_c.Call.Return(summoner, err)
	return _c
}

func (_c *MockStore_GetSummonerByRegionNameTag_Call) RunAndReturn(run func(ctx context.Context, region string, name string, tag string) (*store.Summoner, error)) *MockStore_GetSummonerByRegionNameTag_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockStore
func (_mock *MockStore) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockStore_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Rollback(ctx any) *MockStore_Rollback_Call {
	return &MockStore_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockStore_Rollback_Call) Run(run func(ctx context.Context)) *MockStore_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Rollback_Call) Return(err error) *MockStore_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockStore_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSummoner provides a mock function for the type MockStore
func (_mock *MockStore) SearchSummoner(ctx context.Context, name string) ([]*store.Summoner, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchSummoner")
	}

	var r0 []*store.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*store.Summoner, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*store.Summoner); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SearchSummoner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSummoner'
type MockStore_SearchSummoner_Call struct {
	*mock.Call
}

// SearchSummoner is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStore_Expecter) SearchSummoner(ctx any, name any) *MockStore_SearchSummoner_Call {
	return &MockStore_SearchSummoner_Call{Call: _e.mock.On("SearchSummoner", ctx, name)}
}

func (_c *MockStore_SearchSummoner_Call) Run(run func(ctx context.Context, name string)) *MockStore_SearchSummoner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SearchSummoner_Call) Return(summoners []*store.Summoner, err error) *MockStore_SearchSummoner_Call {
	_c.Call.Return(summoners, err)
	return _c
}

func (_c *MockStore_SearchSummoner_Call) RunAndReturn(run func(ctx context.Context, name string) ([]*store.Summoner, error)) *MockStore_SearchSummoner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRankByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) UpdateRankByPUUID(ctx context.Context, puuid string, req store.UpdateRank) (*store.Rank, error) {
	ret := _mock.Called(ctx, puuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRankByPUUID")
	}

	var r0 *store.Rank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.UpdateRank) (*store.Rank, error)); ok {
		return returnFunc(ctx, puuid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.UpdateRank) *store.Rank); ok {
		r0 = returnFunc(ctx, puuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Rank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, store.UpdateRank) error); ok {
		r1 = returnFunc(ctx, puuid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateRankByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRankByPUUID'
type MockStore_UpdateRankByPUUID_Call struct {
	*mock.Call
}

// UpdateRankByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
//   - req store.UpdateRank
func (_e *MockStore_Expecter) UpdateRankByPUUID(ctx any, puuid any, req any) *MockStore_UpdateRankByPUUID_Call {
	return &MockStore_UpdateRankByPUUID_Call{Call: _e.mock.On("UpdateRankByPUUID", ctx, puuid, req)}
}

func (_c *MockStore_UpdateRankByPUUID_Call) Run(run func(ctx context.Context, puuid string, req store.UpdateRank)) *MockStore_UpdateRankByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 store.UpdateRank
		if args[2] != nil {
			arg2 = args[2].(store.UpdateRank)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_UpdateRankByPUUID_Call) Return(rank *store.Rank, err error) *MockStore_UpdateRankByPUUID_Call {
	_c.Call.Return(rank, err)
	return _c
}

func (_c *MockStore_UpdateRankByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string, req store.UpdateRank) (*store.Rank, error)) *MockStore_UpdateRankByPUUID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSummonerByPUUID provides a mock function for the type MockStore
func (_mock *MockStore) UpdateSummonerByPUUID(ctx context.Context, puuid string, req store.UpdateSummoner) (*store.Summoner, error) {
	ret := _mock.Called(ctx, puuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSummonerByPUUID")
	}

	var r0 *store.Summoner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.UpdateSummoner) (*store.Summoner, error)); ok {
		return returnFunc(ctx, puuid, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, store.UpdateSummoner) *store.Summoner); ok {
		r0 = returnFunc(ctx, puuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Summoner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, store.UpdateSummoner) error); ok {
		r1 = returnFunc(ctx, puuid, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateSummonerByPUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSummonerByPUUID'
type MockStore_UpdateSummonerByPUUID_Call struct {
	*mock.Call
}

// UpdateSummonerByPUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - puuid string
//   - req store.UpdateSummoner
func (_e *MockStore_Expecter) UpdateSummonerByPUUID(ctx any, puuid any, req any) *MockStore_UpdateSummonerByPUUID_Call {
	return &MockStore_UpdateSummonerByPUUID_Call{Call: _e.mock.On("UpdateSummonerByPUUID", ctx, puuid, req)}
}

func (_c *MockStore_UpdateSummonerByPUUID_Call) Run(run func(ctx context.Context, puuid string, req store.UpdateSummoner)) *MockStore_UpdateSummonerByPUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 store.UpdateSummoner
		if args[2] != nil {
			arg2 = args[2].(store.UpdateSummoner)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_UpdateSummonerByPUUID_Call) Return(summoner *store.Summoner, err error) *MockStore_UpdateSummonerByPUUID_Call {
	_c.Call.Return(summoner, err)
	return _c
}

func (_c *MockStore_UpdateSummonerByPUUID_Call) RunAndReturn(run func(ctx context.Context, puuid string, req store.UpdateSummoner) (*store.Summoner, error)) *MockStore_UpdateSummonerByPUUID_Call {
	_c.Call.Return(run)
	return _c
}
